### ISSUE TITLE
handlebars

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-generator#1]
We don't need to do a lot of templating and templates/string injection should definitely **NOT** be used for code. We learned that lesson the first time with the old generator.

Common situations where we need templates to inject things dynamically:
- comments (file names)
- function names (possibly). For example hook/filter names so that they aren't anonymous functions. This makes debugging easier.
- readme files

Any JSON file should never use templating and instead should be read in, modified, and written back out.

### Generators
- [ ] App
- [x] Services
- [x] Models
- [ ] Middleware
- [ ] Hooks
- [ ] Filters

**Comment by slajax** [comment]
done for service generators in #21

**Comment by ekryski** [comment]
Sweet I'll have to pull this in and update the app, hook and middleware generators.

**Comment by slajax** [comment]
@ekryski we can discuss in our chat this afternoon about moving stuff like the handler bars renderer out into a global util so that all the generators can leverage it.
