### ISSUE TITLE
helmet + ssl by default

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-generator#11]
https://github.com/helmetjs/helmet

I discovered it through this article: https://nodesource.com/blog/nine-security-tips-to-keep-express-from-getting-pwned/?utm_source=nodeweekly&utm_medium=email

**Comment by marshallswain** [comment]
We can enable this with SSL, because it automatically enables Strict Transport Security, which disables http.

**Comment by daffl** [comment]
@ekryski Added helmet today into the generator via https://github.com/feathersjs/generator-feathers/pull/166 (and we'll get it in the newest version when porting those changes over). I don't think we can easily do SSL, generating and managing valid certs is pretty provider specific.
