### ISSUE TITLE
readme + documentation

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-generator#12]
Could somebody please add some instructions on how to use this to help with development?
@ekryski

**Comment by ekryski** [comment]
@marshallswain it's more of a utility module. You can call it directly in code but it's sort of meant to have an some other interface to it. There is a bunch of docs in the readme but obviously you've seen that.

Let me know what is unclear and I'll add docs to hopefully clarify. I was thinking that I might add a diagram and document the API for the lifecycle of a generator. Hopefully that will make it easier to grok.

**Comment by slajax** [comment]
captured in #52
