### ISSUE TITLE
redis adapter

### ISSUE THREAD

**Issue by slajax** [feathersjs/feathers-generator#34]
### overview

implement a redis adapter 

### tasks
- [ ] add model choice
- [ ] add model choice dependencies
- [ ] add model templates
- [ ] test that it works

**Comment by daffl** [comment]
I don't think that one is official/ready yet.

**Comment by slajax** [comment]
All good, this can wait until it is then.

**Comment by ekryski** [comment]
Yeah the redis adapter isn't ready yet. One of us on the core team will need to take a proper look at the first crack at implementation. This is likely to be the trickiest adapter.

**Comment by daffl** [comment]
Closing since there probably won't be a fully query syntax compatible Redis adapter.
