### ISSUE TITLE
mongoose >= 4.11.0 logs a deprecation warning for generated service

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-generator#67]
> feathers generate service
Choose mongoose
Choose /messages
node ./src
and the console logs

```text
(node:4447) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

```

**Comment by daffl** [comment]
Looks like we'll have to change https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/templates/mongoose.js#L6 to

```js
mongoose.connect(app.get('mongodb'), {
});

**Comment by oussamaABID** [comment]
WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.

>  "mongoose": "5.0.0-rc2",

just :  
```
mongoose.connect(app.get('mongodb'), {
});
```

**Comment by daffl** [comment]
I'd welcome a PR just like https://github.com/feathersjs/generator-feathers/pull/255 and be happy to publish it once 5.0.0 is official.
