### ISSUE TITLE
errors inside generators are surpressed

### ISSUE THREAD

**Issue by slajax** [feathersjs/feathers-generator#9]
As I was creating a generator for services I noticed generators are suppressing errors so there are no stack trace.

For example: an undefined variables inside [the scope of the generator function](https://github.com/feathersjs/feathers-generator/blob/master/src/app/generator.js#L19-L65) is suppressed and provides no stack trace but causes the program to halt.

It's not the end of the world but it's probably worth fixing so we at least get a stack trace for debugging purposes so we don't waste time on typos etc. 

I'll try to track down the reason for this as I go and suggest a solution.

**Comment by slajax** [comment]
Also, if someone wants to give me access to labels, that would be rad.

**Comment by ekryski** [comment]
@slajax sorry dude around this repo it's easiest to ping me in slack. You don't have access to labels?

**Comment by slajax** [comment]
@ekryski no worries, I'll ping you there next time. I don't seem to be able to edit labels or do any of the other fun issue management stuff. No big deal, but if you want me to, I can help manage those things in any repo that I'm active in.
